name: General Issue
description: Report a general issue or ask a question
title: "[Issue]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue or question.
      placeholder: Describe your issue or question...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (if applicable)
      description: Please provide the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Add any other information about the issue here.
      placeholder: Additional details...
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0